dataset:
  data_type: mpdd
  data_path: ./MPDD
  obj: tubes
  shot: 2
  batch_size: 10
  img_size: 224
  input_channel: 3
  supp_set: ./mpdd_supp_set/2/t_2_1.pt
  include_maddern_transform: true
  alpha: 0.48

model:
  coreset_sampling_ratio: 0.05
  num_neighbors: 1

project:
  seed: 668
  save_dir: results/mpdd-bbr-MT/

trainer:
  epochs: 50
  inferences: 1
  lr: 0.0001
  momentum: 0.9
  stn_mode: rotation_scale
